#!/bin/bash
echo $VOLUME
set -x
if [[ "$1" = "+" ]]; then
	brightnessctl set +5% | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > $WOBSOCK	
elif [[ "$1" = "-" ]]; then
	brightnessctl set 5%- | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > $WOBSOCK
else
	echo "Please run as changebright + or changebright -"
fi
