#!/bin/bash
echo $VOLUME
set -x
if [[ "$1" = "+" ]]; then
	amixer sset Master 5%+ | sed -En 's/.*\[([0-9]+)%\].*/\1/p' | head -1 > $WOBSOCK && beep
elif [[ "$1" = "-" ]]; then
	amixer sset Master 5%- | sed -En 's/.*\[([0-9]+)%\].*/\1/p' | head -1 > $WOBSOCK && beep
else
	echo "Please run as changevolume + or changevolume -"
fi
