exec-once = /usr/libexec/lxqt-policykit-agent

exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data

exec-once = systemctl --user start swaync.service
exec-once = systemctl --user start hyprland-shell-waybar.service
exec-once = systemctl --user start hypridle.service
