# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# Some default env vars.

exec-once = gsettings set org.gnome.desktop.interface cursor-theme Bibata-Modern-Classic

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/windowrules.conf

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/


general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    resize_on_border = yes
    no_border_on_floating = yes
    gaps_in = 5
    gaps_out = 10
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 8
    shadow {
      enabled = true
      range = 4
      render_power = 3
      color = rgba(1a1a1aee) 
    }
}

animations {
    enabled = true
    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # you probably want this
}

misc {
    disable_hyprland_qtutils_check = true
    #disable_hyprland_guiutils_check = true
}
