# Bibata modern classic theme cursor. Installing:
# 
# dnf dnf copr enable cjuniorfox/hyprland-shell 
# dnf install bibata-cursor-theme

HYPRCURSOR_THEME=Bibata-Modern-Classic
HYPRCURSOR_SIZE=24
XCURSOR=Bibata-Modern-Classic,24
